name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        compile: [windows]
        build: [release]
        include:
          - compile: windows
            os: windows-latest

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.compile }}-${{ matrix.build }} Build
    steps:
      - uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Restore action cache
        uses: actions/cache@v3
        with:
          key: cache-build-${{ matrix.compile }}
          path: |
            export/${{ matrix.build }}/${{ matrix.compile }}/haxe/
            export/${{ matrix.build }}/${{ matrix.compile }}/obj/
            .haxelib/

      - name: Setup Haxelib
        run: |
          haxelib setup .haxelib/
          haxelib install format --quiet
          haxelib install hxp --quiet

      - name: Install hxcpp-debug-server
        if: ${{ matrix.build == 'debug' }}
        run: haxelib install hxcpp-debug-server --quiet

      - name: Install haxelibs
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Compile (32-bit)
        if: ${{ matrix.build == '32bit' }}
        run: haxelib run lime build ${{ matrix.compile }} -${{ matrix.build }} -officialBuild -32 -D HXCPP_M32

      - name: Compile (64-bit)
        if: ${{ matrix.build != '32bit' }}
        run: |
          haxelib run lime build ${{ matrix.compile }} -${{ matrix.build }} -officialBuild -64

      - name: Uploading artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.compile }}-${{ matrix.build }}
          path: export/${{ matrix.build }}/${{ matrix.compile }}/bin
          if-no-files-found: error

      - name: Uploading artifact (executable windows)
        if: ${{ matrix.compile == 'windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: executableOnly-${{ matrix.compile }}-${{ matrix.build }}
          path: export/${{ matrix.build }}/${{ matrix.compile }}/bin/PsychEngine.exe

      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-${{ matrix.compile }}") {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v3
        with:
          key: cache-build-${{ matrix.compile }}
          path: |
            export/${{ matrix.build }}/${{ matrix.compile }}/haxe/
            export/${{ matrix.build }}/${{ matrix.compile }}/obj/
            .haxelib/
